language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: glow-mdsol
  password:
    secure: lnI+CqRrfqv7tItVQdZP9gFLpVyiqQQJhtOwzQcb6PpWQxzi2I2TuSjgjLX1surbVGr+NJRMXf/x+ohuM3MpBFxYyFFpwO20rtfnoEXTId7C9RwnHbya3QY4zzm9Z/xGQyHZOvXtcwMkEs5LQdxZoqVT6Hxrb2WayaFuA4LbpQ+q8XQB3t8/JPX7UVHhHGi82Ev1kjhEJwnKWgJ/DQyvwe89I5x7gpYAfz2FNZS8bnaJpeggcG1OoRF3imNVUArLpGNaveWA5LcZyhtHIYTMzcQID3BgKa2k5k+DmkoDjecTW1ejWe+CkO2GpZ5o859DYBgvKAPpSsODxo5kr7XkQrB6Cx6nLLJ20plpmSjqQtdoKYBjDVOvjHTA+JDOQB//pTNCOES1sW4JJLtIqLtiOAl/oHhWH/5M3FXhH4L6S78blXwCsnBa3LXAz1KnyIRXZANF6RhB8rzuKQ2Jp/HvDYx6hR5/NwHTlcx3wa4JcvVzelOj/G8fbRXVG8UoiYs2So3+4yzdSp3qxbE/tQgOx9Q7rXn/RH2+WdZUIkf3p4VzOclxDDIdumhvhi7igf726NNvDDMw+yRL3icXsI4w7pW+gvJWmE8VI64AltZlq6m42ZgUoOT9dJXsU6iy3QCzqHhrYipkChqBKA+7gTniwN7qy9jrFQsGI7HUXAyZrvA=
  on:
    tags: true
    python: 3.6
  distributions: sdist bdist_wheel
