language: python
jobs:
  fast_finish: true
  include:
  - python: "2.7"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: pypy
install: 
  - python setup.py install
script: 
  - python setup.py test
deploy:
  provider: pypi
  user: glow-mdsol
  edge: true
  password:
    secure: RRsj56V7oLnMTM52tZd3enKGzQ5A1uU5OPQRUqjc47XoQCH1900CFTpF0kg9usDQSApbl2rRhRwdmqYR+4S+v7JMoYMGYUfJe1cDkgRr3iGs96t3zjnxqppfaMitO6JUIhpOwO+29xcANIWbchjN7N3T+KkIOHxFhlZE6dfL6ZZx0eQjcD58TqzCWYTF0OSY+v+ZZpleiU8t7niHzWhgM+XOpUzgWGWcGev782mG9FeL6Vr5jtfeAeacj29kxNjwmQj5wTqcyOAzgouf3hG4rvdjEWa3RCu8ohjsC2SgaPIbLeNVIsVdxK8/J0LjCNy7mvoInfEmlvVYowA8hpVTH+cbD7BbJmdF4QeUhekUxL06dWfQiygfyILS7vaxDX01fWowJGq5Iq/zp6Wd4ZUZx7B/EKw/Ysb5+NAe+GZHVthYvO63rH9gRocdlcBM2GOYsWcxVRjUV7NOjRhrFzxgudBe3dowcFBiPvHHXN/+dthVvHQaw5On095vT0t9ogBvUC5gKlRMiVW2Gdje+Hl/lZ4zF8cPZM3eRhMqLZ/K5H3BqW+MTiQYHAwd5T1Oiz/yrq0EBOhdDYiC/aqSREPLHwpqbJ3hQogHrO8JPrkUjGhTffNAT6B428b81hBWA/zB+Im8HCMZ5KoQm9B7Z7T2Bh2CihKwzrNO3KgTyyXyxKI=
  on:
    tags: true
    python: 3.7
  distributions: sdist bdist_wheel
  skip_existing: true
